### ISSUE TITLE
PHRASE FILTERING NOT WORKING

### ISSUE THREAD

**Issue by G-i-o** [ice2heart/protectron#5]
Hello.

To my understanding, if I input few words between quotations to the "blacklist_add" command, Protectron should delete all messages which contain all the words in the quotation marks, typed in the same order. So, if I type:
`blacklist_add "Today I am spamming you"`
Protectron should delete all messages and only those messages containing the sentence "Today I am spamming you" but not those containing the very same words in any other order or mixed with other words.

Apparently, this function is not currently working. Protectron does not delete any message containing the same sentence.

We hope this can be solved as this is a very important feature and without it we continue to get flooded by spam.

Much appreciated.
Gio

**Comment by ice2heart** [comment]
Hi, Probably you looking the wrong bot. 
You want @ProtectronBot but this is @protectron9000_bot . Please ask owner of the bot.

**Comment by G-i-o** [comment]
Thank You for your prompt reply and tips Ice2heart
and apologies for confusing the two projects.

Best wishes to yours.
